Add support for version 2.1.0
phpviet/omnipay-vnpay pull request #4
Opened 2023-09-12 22:42 UTC by bangnokia

Pull request nảy của minh update dependencies cho package, hỗ trợ PHP 7.4 -> 8.2
Support minimum version VNPay 2.1.0, drop các thuật toán mã hóa cũ như md5 và sha256 và version api cũ
Update lại mock response trong tests
Đây là breaking change vì mình nghĩ không có lí do gì maintain các phiên bản cũ hơn cả.

2023-09-18 04:47 UTC, vuongxuongminh commented
Cảm ơn PR của bạn, mình sẽ review trong tuần này nha.

2023-09-24 13:03 UTC, vuongxuongminh requested changes

2023-09-24 13:03 UTC, vuongxuongminh commented on src/Message/Concerns/RequestSignature.php
> +    protected function generateSignature(string $hashType = 'sha512'): string
param này không còn sử dụng nữa nên xóa đi?

2023-09-24 13:03 UTC, vuongxuongminh commented on composer.json
> +        "php-http/guzzle7-adapter": "^1.0"
`php-http/guzzle7-adapter` nên chỉ là dev dependency.

2023-09-24 13:03 UTC, vuongxuongminh commented on composer.json
> +            "php-http/discovery": true
Chúng ta không cần auto discovery (do chúng ta đã explicit dev dependency), auto discovery chỉ cần đối với user.

2024-10-04 09:50 UTC, phuongnamsoft approved these changes

2025-10-28 19:51 UTC, closed without merging